/// Generates fixture SQL for local development.
/// Usage: cargo run --example gen_fixtures > fixtures.sql
use base64::{Engine, engine::general_purpose::STANDARD};
use pbkdf2::pbkdf2_hmac;
use sha2::Sha256;

struct User {
    username: &'static str,
    first_name: &'static str,
    last_name: &'static str,
    email: &'static str,
    password: &'static str,
    is_superuser: bool,
    is_staff: bool,
}

const ITERATIONS: u32 = 600_000;

fn django_hash(password: &str, salt: &str) -> String {
    let mut output = [0u8; 32];
    pbkdf2_hmac::<Sha256>(password.as_bytes(), salt.as_bytes(), ITERATIONS, &mut output);
    format!("pbkdf2_sha256${}${}${}", ITERATIONS, salt, STANDARD.encode(output))
}

fn main() {
    let users = vec![
        User {
            username: "admin",
            first_name: "Admin",
            last_name: "User",
            email: "admin@coworking.local",
            password: "adminpass123",
            is_superuser: true,
            is_staff: true,
        },
        User {
            username: "alice",
            first_name: "Alice",
            last_name: "Martin",
            email: "alice@coworking.local",
            password: "alicepass123",
            is_superuser: false,
            is_staff: true,
        },
        User {
            username: "bob",
            first_name: "Bob",
            last_name: "Dupont",
            email: "bob@coworking.local",
            password: "bobpass123",
            is_superuser: false,
            is_staff: true,
        },
    ];

    println!("-- Fixture data for local development");
    println!("-- Generated by: cargo run --example gen_fixtures");
    println!("-- DO NOT use in production\n");

    println!("INSERT INTO auth_user");
    println!("  (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)");
    println!("VALUES");

    let rows: Vec<String> = users
        .iter()
        .enumerate()
        .map(|(i, u)| {
            let hash = django_hash(u.password, &format!("fixturesalt{i:02}"));
            format!(
                "  ('{}', NULL, {}, '{}', '{}', '{}', '{}', {}, true, NOW())",
                hash, u.is_superuser, u.username, u.first_name, u.last_name, u.email, u.is_staff,
            )
        })
        .collect();

    println!("{};", rows.join(",\n"));

    eprintln!("\nCredentials:");
    for u in &users {
        eprintln!("  {} / {}", u.username, u.password);
    }
}
